class Solution {
public:
    int trailingZeroes(int n) {
         // every leading zero is generated by 2*5 and cnt of 5 << cnt of 2;
        int ans = 0;
      while(n / 5 > 0){
            ans += n / 5;
           n = n /5 ;
      }
       return ans;
    }
};
